version: '3.9'

services:
  orchestrator-service:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/orchestra
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - orchestrator-db

  orchestrator-db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=tester
      - POSTGRES_PASSWORD=tester
      - POSTGRES_DB=test_law
    expose:
      - 5435
    ports:
      - 5435:5435
    command: 
      -p 5435

volumes:
  postgres_data:
