# Generated by Django 4.2 on 2023-04-30 12:31

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("owner_id", models.IntegerField()),
                ("status", models.CharField(max_length=50)),
                (
                    "menu",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50), size=None
                    ),
                ),
                (
                    "quantity",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), size=None
                    ),
                ),
                ("price", models.IntegerField()),
            ],
            options={"ordering": ["created_at"],},
        ),
    ]
