# Generated by Django 4.2 on 2023-04-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order", name="price", field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(default="waiting for payment", max_length=50),
        ),
    ]
