# Generated by Django 4.2 on 2023-04-30 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_alter_order_price_alter_order_status"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="price",),
    ]
