# Generated by Django 4.2 on 2023-04-30 12:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_remove_order_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="price",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), default=[0], size=None
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="total_price",
            field=models.IntegerField(default=0),
        ),
    ]
