# Generated by Django 4.2 on 2023-05-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0006_remove_order_address_remove_order_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="order",
            name="name",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="order",
            name="phone",
            field=models.CharField(default="", max_length=25),
        ),
    ]
