# Generated by Django 4.2 on 2023-05-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0007_order_address_order_name_order_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order", name="address", field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="order", name="name", field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="order", name="phone", field=models.CharField(max_length=25),
        ),
    ]
